Vagrant.configure("2") do |config|
    config.vm.box = "debian/stretch64"
    config.vm.hostname = "ssg-comments-test"

    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 5001, host: 5001
    config.vm.network "forwarded_port", guest: 22, host: 2223

    config.vm.provision :ansible do |ansible|
        ansible.playbook = "test-deploy.yml"
        ansible.verbose = true
        ansible.extra_vars = {
            flaskapp_name: "ssg_comments",
            flasskapp_src_dir: Dir.pwd  + "/../",
            flasskapp_install_dir: "/home/vagrant/",
            flaskapp_config_path: "/home/vagrant/ssg_comments/test/config.py",
            flaskapp_port: 5001,
            flaskapp_httpd_port: 8080
        }
    end

end
