
- name: Install NTP.
  apt:
    name: ntp
    state: present
    update_cache: yes
  notify: restart ntp
  become: true

- name: Enable the NTP daemon.
  service:
    name: ntp
    state: started
    enabled: yes
  become: true
